' Create a class diagram and justify an inheritance hierarchy that could be used to represent the following classes : shape, rectangle, square, circle, ellipse, triangle


 

@startuml

class Shape {
    +getArea()
    +getPerimeter()
}
class Rectangle extends Shape{
    +getLength()
    +getBreadth()
}

class Square extends Rectangle{
    +getSide()
}

class Circle extends Ellipse {
    +getRadius()
}

class Ellipse extends Shape{
    +getMajorAxis()
    +getMinorAxis()
}

class Triangle extends Shape{
    +getSide1()
    +getSide2()
    +getSide3()
}
@enduml